#pragma once

#include "../VersioningStruct.h"

namespace Wwise::Exports {
	// Root
	inline VersioningStruct<uintptr_t> func_Wwise_Root_IsRestoreSinkRequested;
	inline VersioningStruct<uintptr_t> func_Wwise_Root_IsUsingDummySink;

	// IAkStreamMgr
	// Only has a single pointer, and is protected https://www.audiokinetic.com/library/2015.1.9_5624/?source=SDK&id=class_a_k_1_1_i_ak_stream_mgr_a85c6043c1a45f13b7df2f05729248b1f.html
	inline VersioningStruct<uintptr_t> func_Wwise_IAkStreamMgr_m_pStreamMgr;

	// MemoryMgr
	inline VersioningStruct<uintptr_t> func_Wwise_Memory_CheckPoolId;
	inline VersioningStruct<uintptr_t> func_Wwise_Memory_CreatePool;
	inline VersioningStruct<uintptr_t> func_Wwise_Memory_DestroyPool;
	inline VersioningStruct<uintptr_t> func_Wwise_Memory_Falign;
	inline VersioningStruct<uintptr_t> func_Wwise_Memory_GetBlock;
	inline VersioningStruct<uintptr_t> func_Wwise_Memory_GetBlockSize;
	inline VersioningStruct<uintptr_t> func_Wwise_Memory_GetMaxPools;
	inline VersioningStruct<uintptr_t> func_Wwise_Memory_GetNumPools;
	inline VersioningStruct<uintptr_t> func_Wwise_Memory_GetPoolAttributes;
	inline VersioningStruct<uintptr_t> func_Wwise_Memory_GetPoolMemoryUsed;
	inline VersioningStruct<uintptr_t> func_Wwise_Memory_GetPoolName;
	inline VersioningStruct<uintptr_t> func_Wwise_Memory_GetPoolStats;
	inline VersioningStruct<uintptr_t> func_Wwise_Memory_IsInitialized;
	inline VersioningStruct<uintptr_t> func_Wwise_Memory_Malign;
	inline VersioningStruct<uintptr_t> func_Wwise_Memory_Malloc;
	inline VersioningStruct<uintptr_t> func_Wwise_Memory_Free;
	inline VersioningStruct<uintptr_t> func_Wwise_Memory_ReleaseBlock;
	inline VersioningStruct<uintptr_t> func_Wwise_Memory_SetMonitoring;
	inline VersioningStruct<uintptr_t> func_Wwise_Memory_SetPoolName;
	inline VersioningStruct<uintptr_t> func_Wwise_Memory_Term;

	// Monitor
	inline VersioningStruct<uintptr_t> func_Wwise_Monitor_PostCode;

	// Motion Engine
	inline VersioningStruct<uintptr_t> func_Wwise_Motion_AddPlayerMotionDevice;
	inline VersioningStruct<uintptr_t> func_Wwise_Motion_RegisterMotionDevice;
	inline VersioningStruct<uintptr_t> func_Wwise_Motion_RemovePlayerMotionDevice;
	inline VersioningStruct<uintptr_t> func_Wwise_Motion_SetPlayerListener;
	inline VersioningStruct<uintptr_t> func_Wwise_Motion_SetPlayerVolume;

	// Music Engine
	inline VersioningStruct<uintptr_t> func_Wwise_Music_GetDefaultInitSettings;
	inline VersioningStruct<uintptr_t> func_Wwise_Music_GetPlayingSegmentInfo;
	inline VersioningStruct<uintptr_t> func_Wwise_Music_Init;
	inline VersioningStruct<uintptr_t> func_Wwise_Music_Term;

	// Sound Engine
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_AddBehaviorExtension;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_CancelBankCallbackCookie;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_CancelEventCallback;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_CancelEventCallbackCookie;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_ClearBanks;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_ClearPreparedEvents;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_CloneActorMixerEffect;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_CloneBusEffect;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_DynamicDialogue_ResolveDialogueEvent_UniqueID;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_DynamicDialogue_ResolveDialogueEvent_Char;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_DynamicSequence_Break;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_DynamicSequence_Close;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_DynamicSequence_LockPlaylist;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_DynamicSequence_Open;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_DynamicSequence_Pause;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_DynamicSequence_Play;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_DynamicSequence_Resume;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_DynamicSequence_Stop;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_DynamicSequence_UnlockPlaylist;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_ExecuteActionOnEvent_UniqueID;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_ExecuteActionOnEvent_Char;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_g_PlayingID;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_GetDefaultInitSettings;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_GetDefaultPlatformInitSettings;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_GetIDFromString;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_GetPanningRule;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_GetSourcePlayPosition;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_GetSpeakerConfiguration;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_Init;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_IsInitialized;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_LoadBank_BankID_MemPoolID;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_LoadBank_Void_UInt32_BankID;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_LoadBank_BankID_Callback;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_LoadBank_Void_UInt32_Callback;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_LoadBank_Char_MemPoolID;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_LoadBank_Char_Callback;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_LoadBankUnique;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_PlaySourcePlugin;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_PostEvent_Char;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_PostEvent_UniqueID;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_PostTrigger_TriggerID;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_PostTrigger_Char;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_PrepareBank_BankID_Callback;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_PrepareBank_BankID_BankContent;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_PrepareBank_Char_Callback;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_PrepareBank_Char_BankContent;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_PrepareEvent_EventID_UInt32;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_PrepareEvent_EventID_UInt32_Callback_Void;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_PrepareEvent_Char_UInt32;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_PrepareEvent_Char_UInt32_Callback_Void;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_PrepareGameSyncs_UInt32_UInt32_UInt32_Callback_Void;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_PrepareGameSyncs_UInt32_UInt32_UInt32;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_PrepareGameSyncs_Char_Char_UInt32_Callback_Void;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_PrepareGameSyncs_Char_Char_UInt32;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_Query_GetActiveGameObjects;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_Query_GetActiveListeners;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_Query_GetCustomPropertyValue_Int32;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_Query_GetCustomPropertyValue_Real32;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_Query_GetEventIDFromPlayingID;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_Query_GetGameObjectAuxSendValues;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_Query_GetGameObjectDryLevelValue;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_Query_GetGameObjectFromPlayingID;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_Query_GetIsGameObjectActive;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_Query_GetListenerPosition;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_Query_GetListenerSpatialization;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_Query_GetMaxRadius_RadiusList;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_Query_GetMaxRadius_GameObject;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_Query_GetObjectObstructionAndOcclusion;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_Query_GetPlayingIDsFromGameObject;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_Query_GetPosition;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_Query_GetPositioningInfo;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_Query_GetRTPCValue_RTPCID;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_Query_GetRTPCValue_Char;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_Query_GetState_StateGroupID;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_Query_GetState_Char;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_Query_GetSwitch_SwitchGroupID;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_Query_GetSwitch_Char;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_Query_QueryAudioObjectIDs_UniqueID;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_Query_QueryAudioObjectIDs_Char;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_RegisterBusVolumeCallback;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_RegisterCodec;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_RegisterGameObj;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_RegisterGlobalCallback;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_RegisterPlugin;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_RemoveBehavioralExtension;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_RenderAudio;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_ResetRTPCValue_RTPCID;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_ResetRTPCValue_Char;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_SeekOnEvent_UniqueID_Int32;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_SeekOnEvent_Char_Int32;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_SeekOnEvent_UniqueID_Float;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_SeekOnEvent_Char_Float;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_SetActiveListeners;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_SetActorMixerEffect;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_SetAttenuationScalingFactor;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_SetBankLoadIOSettings;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_SetBusEffect_UniqueID;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_SetBusEffect_Char;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_SetEffectParam;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_SetGameObjectAuxSendValues;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_SetGameObjectOutputBusVolume;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_SetListenerPipeline;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_SetListenerPosition;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_SetListenerScalingFactor;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_SetListenerSpatialization;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_SetMaxNumVoicesLimit;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_SetMultiplePositions;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_SetObjectObstructionAndOcclusion;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_SetPanningRule;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_SetPosition;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_SetPositionInternal;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_SetRTPCValue_RTPCID;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_SetRTPCValue_Char;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_SetState_StateGroupID;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_SetState_Char;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_SetSwitch_SwitchGroupID;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_SetSwitch_Char;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_SetVolumeThreshold;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_StartOutputCapture;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_StopAll;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_StopOutputCapture;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_StopPlayingID;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_StopSourcePlugin;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_Term;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_UnloadBank_BankID_MemPoolID;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_UnloadBank_BankID_Callback;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_UnloadBank_Char_MemPoolID;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_UnloadBank_Char_Callback;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_UnloadBankUnique;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_UnregisterAllGameObj;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_UnregisterGameObj;
	inline VersioningStruct<uintptr_t> func_Wwise_Sound_UnregisterGlobalCallback;

	// StreamMgr - This Section has way too many dependancies for us to really use it.
	//inline VersioningStruct<uintptr_t> func_Wwise_Stream_AddLanguageChangeObserver;
	//inline VersioningStruct<uintptr_t> func_Wwise_Stream_Create;
	//inline VersioningStruct<uintptr_t> func_Wwise_Stream_CreateDevice;
	//inline VersioningStruct<uintptr_t> func_Wwise_Stream_DestroyDevice;
	//inline VersioningStruct<uintptr_t> func_Wwise_Stream_FlushAllCaches;
	//inline VersioningStruct<uintptr_t> func_Wwise_Stream_GetCurrentLanguage;
	//inline VersioningStruct<uintptr_t> func_Wwise_Stream_GetDefaultDeviceSettings;
	//inline VersioningStruct<uintptr_t> func_Wwise_Stream_GetDefaultSettings;
	//inline VersioningStruct<uintptr_t> func_Wwise_Stream_GetFileLocationResolver;
	//inline VersioningStruct<uintptr_t> func_Wwise_Stream_GetPoolID;
	//inline VersioningStruct<uintptr_t> func_Wwise_Stream_RemoveLanguageChangeObserver;
	//inline VersioningStruct<uintptr_t> func_Wwise_Stream_SetCurrentLanguage;
	//inline VersioningStruct<uintptr_t> func_Wwise_Stream_SetFileLocationResolver;

	void Initialize();
}